baseURL = 'claredonegancreative.com'
languageCode = 'en-us'
title = 'Clare Donegan'
copyright = 'Clare Donegan 2026'

theme = 'hugo-book'

# Needed for mermaid/katex shortcodes
[markup]
[markup.goldmark.renderer]
unsafe = true

[params]
BookSearch = false
# Use docs as the main book section
BookSection = "docs"
# Disable page navigation buttons
BookDisableNavigation = true
# Favicon
BookFavicon = "favicon.png"

# Hugo Book theme menus
[menu]
[[menu.after]]
name = "Contact"
url = "/docs/contact/"
weight = 1

[[menu.after]]
name = "Instagram"
url = "https://www.instagram.com/clarerdonegan/"
weight = 5

# For github deployment
# https://gohugo.io/host-and-deploy/host-on-github-pages/
[caches]
  [caches.images]
    dir = ':cacheDir/images'